<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentification</title>
</head>
<body>
<form action="" method="post">
        <span>Pseudo :</span>
        <input type="text" placeholder="..." name="pseudo">
        <span>Mot de passe :</span>
        <input type="password" placeholder="..." name="password"> 
        <button>Se connecter</button>
    </form>
</body>
</html>