<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
</head>

<body>
    <a href="index.php">Accueil</a>
    <a href="inscription.php">Inscription</a>
    <a href="Authentification.php">Authentification</a>
    <form action="" method="post"><br>
        <span>Pseudo :</span>
        <input type="text" placeholder="..." name="pseudo">
        <span>Mot de passe :</span>
        <input type="password" placeholder="..." name="password">
        <button>S'inscrire</button>
    </form>
</body>

</html>