<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rédiger un article</title>
</head>

<body>
    <a href="index.php">Accueil</a>
    <a href="compte.php">Tableau de bord</a>
    <a href="index.php">Deconnexion</a>
    <h1>Rédiger un article</h1>
    <form action="redactionArticle.php" method="post" enctype="multipart/form-data">
        <input type="text" placeholder="Titre" name="title">
        <textarea placeholder="Contenu" name="content" id="" cols="30" rows="5"></textarea>
        <span>
        <input type="file" name="fichier" accept="image/png, image/jpeg">
        <input type="hidden" name="MAX_FILE_SIZE">
        </span>
        <button type="submitt">Publier</button>
    </form>
</body>
</html>